# Generated by Django 5.2.17 on 2026-09-12 04:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='대회명')),
                ('description', models.TextField(verbose_name='소개')),
                ('rules', models.TextField(default='개인전 · 외부 데이터 사용 여부는 교수자의 안내를 따릅니다.', verbose_name='규칙')),
                ('opens_at', models.DateTimeField(verbose_name='시작 시각')),
                ('closes_at', models.DateTimeField(verbose_name='마감 시각')),
                ('daily_limit', models.PositiveSmallIntegerField(default=5, verbose_name='문제별 일일 제출 제한')),
                ('invite_code', models.CharField(max_length=80, verbose_name='초대 코드')),
                ('visible', models.BooleanField(default=False, verbose_name='대회 표시')),
                ('finalized_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': '대회',
                'verbose_name_plural': '대회',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('real_name', models.CharField(max_length=60, verbose_name='이름')),
                ('student_id', models.CharField(max_length=30, verbose_name='학번')),
                ('nickname', models.CharField(max_length=40, verbose_name='별명')),
                ('show_real_name', models.BooleanField(default=False, verbose_name='실명 표시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '작업 기록',
                'verbose_name_plural': '작업 기록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arena.contest')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='문제명')),
                ('kind', models.CharField(choices=[('regression', '회귀'), ('binary', '이진분류')], max_length=16, verbose_name='유형')),
                ('metric', models.CharField(choices=[('rmse', 'RMSE'), ('mae', 'MAE'), ('roc_auc', 'ROC-AUC'), ('ap', 'Average Precision')], default='rmse', max_length=12, verbose_name='평가 지표')),
                ('description', models.TextField(verbose_name='예측 대상·설명')),
                ('units', models.CharField(max_length=200, verbose_name='단위·변환')),
                ('source', models.TextField(verbose_name='데이터 출처')),
                ('split_method', models.TextField(verbose_name='분할 방법')),
                ('id_column', models.CharField(default='sample_id', max_length=80, verbose_name='ID 열')),
                ('smiles_column', models.CharField(default='SMILES', max_length=80, verbose_name='SMILES 열')),
                ('target_column', models.CharField(default='target', max_length=80, verbose_name='정답 열')),
                ('feature_columns', models.JSONField(blank=True, default=list, verbose_name='공개 특징 열 (JSON 배열)')),
                ('dataset_version', models.CharField(blank=True, editable=False, max_length=64)),
                ('manifest', models.JSONField(default=dict, editable=False)),
                ('warnings', models.JSONField(default=list, editable=False)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='arena.contest')),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='학년도')),
                ('term', models.CharField(max_length=20, verbose_name='학기')),
            ],
            options={
                'verbose_name': '학년도·학기',
                'verbose_name_plural': '학년도·학기',
                'ordering': ['-year', '-term'],
                'constraints': [models.UniqueConstraint(fields=('year', 'term'), name='semester_unique')],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.semester'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('received_at', models.DateTimeField()),
                ('quota_day', models.DateField()),
                ('path', models.CharField(max_length=220)),
                ('file_hash', models.CharField(max_length=64)),
                ('dataset_version', models.CharField(max_length=64)),
                ('scorer_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', '채점 대기'), ('processing', '채점 중'), ('scored', '채점 완료'), ('error', '서버 오류')], default='pending', max_length=16)),
                ('val_score', models.FloatField(blank=True, null=True)),
                ('test_score', models.FloatField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease', models.UUIDField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '제출',
                'verbose_name_plural': '제출',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinalChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='학번')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '참가 승인'), ('suspended', '참가 정지')], default='pending', max_length=12, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arena.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '참가 신청',
                'verbose_name_plural': '참가 신청',
                'constraints': [models.UniqueConstraint(fields=('user', 'contest'), name='one_membership'), models.UniqueConstraint(fields=('contest', 'student_id'), name='one_student_per_contest')],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'started_at'], name='arena_submi_status_d8d07f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', 'quota_day'], name='arena_submi_user_id_417a5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'problem', 'request_key'), name='idempotent_submission'),
        ),
        migrations.AddConstraint(
            model_name='finalchoice',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='one_final_choice'),
        ),
    ]
