# Generated by Django 5.2.17 on 2026-09-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='quota_exempt',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
