# Generated by Django 5.2.17 on 2026-10-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_submission_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='metric',
            field=models.CharField(choices=[('rmse', 'RMSE'), ('mae', 'MAE'), ('mse', 'MSE'), ('r2', 'R²'), ('pearson', 'Pearson r'), ('spearman', 'Spearman ρ'), ('roc_auc', 'ROC-AUC'), ('ap', 'AUPRC (Average Precision)'), ('log_loss', 'Log Loss'), ('accuracy', 'Accuracy'), ('balanced_accuracy', 'Balanced Accuracy'), ('f1', 'F1'), ('mcc', 'MCC'), ('precision', 'Precision (PPV)'), ('npv', 'NPV (Negative Predictive Value)'), ('recall', 'Recall (Sensitivity)'), ('specificity', 'Specificity')], default='rmse', help_text='순위를 결정하는 주 지표입니다. 같은 유형의 나머지 지표는 참고용으로 함께 계산됩니다.', max_length=24, verbose_name='순위 지표'),
        ),
    ]
